FROM fedora:44
RUN dnf -y -q install gnome-shell gnome-extensions-app dbus-daemon dbus-tools librsvg2 gjs glib2 dconf mesa-dri-drivers xorg-x11-server-Xwayland python3-dbusmock >/dev/null && dnf clean all
